version: '3'
services:
    client:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        command: ./run.sh serve_local
        environment:
            HOST: '0.0.0.0'
            PORT: '8888'
        ports:
            - "8888:8888"
